apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/studyconnect-zhaw/frontend/staging:0.0.10         
        env:
        - name: NEXT_PUBLIC_API_URL
          value: https://api-scmy-studyconnect-staging.pm4.init-lab.ch/api
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: CLIENT_SECRET 
        - name: REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: REDIRECT_URI
        - name: POST_LOGOUT_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: POST_LOGOUT_REDIRECT_URI
        ports:
        - containerPort: 3000