apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/studyconnect-zhaw/backend/staging:0.0.12
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Server=mssql-server;Database=studyconnect;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True; # Add connection string
            - name: MSSQL_SA_PASSWORD
              value: ${MSSQL_SA_PASSWORD}