apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/studyconnect-zhaw/backend/staging:0.0.12
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret           # name of the secret in Rancher/K8s
                  key: MSSQL_SA_PASSWORD       # key inside the secret
            - name: MSSQL_SA_USER
              valueFrom:
                secretKeyRef:
                  name: mssql-secret           # name of the secret in Rancher/K8s
                  key: MSSQL_SA_USER           # key inside the secret
            - name: ConnectionStrings__DefaultConnection
              value: Server=mssql-service.scmy-studyconnect-staging;Database=studyconnect;User Id=$(MSSQL_SA_PASSWORD);Password=$(MSSQL_SA_PASSWORD);TrustServerCertificate=True;