apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: scmy-studyconnect-staging
  labels:
    app: mssql-server
spec:
  type: LoadBalancer  # Change this to LoadBalancer to expose it externally
  selector:
    app: mssql-server
  ports:
    - protocol: TCP
      port: 1433       # Internal port for the service
      targetPort: 1433  # Port on the MSSQL Server container
