apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: scmy-studyconnect-staging
spec:
  template:
    spec:
      containers:
      - name: test-container
        image: busybox:latest
        command: ["/bin/sh", "-c", "echo 'hello' && sleep 5"]
      restartPolicy: Never
  backoffLimit: 1